# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csample.proto\x12\x06sample\"\x1c\n\x0eSampleDataById\x12\n\n\x02id\x18\x01 \x01(\x05\"&\n\nSampleData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t2E\n\nAppService\x12\x37\n\x07\x46indOne\x12\x16.sample.SampleDataById\x1a\x12.sample.SampleData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sample_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAMPLEDATABYID']._serialized_start=24
  _globals['_SAMPLEDATABYID']._serialized_end=52
  _globals['_SAMPLEDATA']._serialized_start=54
  _globals['_SAMPLEDATA']._serialized_end=92
  _globals['_APPSERVICE']._serialized_start=94
  _globals['_APPSERVICE']._serialized_end=163
# @@protoc_insertion_point(module_scope)
